# Generated by Django 4.2.8 on 2024-01-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogAdmin', '0009_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
    ]
